server:
  port: 8980
  servlet:
    context-path: /performance
  compression:
    enabled: true
    mime-types: application/json, application/xml,text/html,image/jpeg,image/png
spring:
  application:
    name: api-performance
  datasource:
    url:
    username:
    password: 
    hikari:
      pool-name: connection-pooling
      connection-timeout: 2000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 3000
      max-lifetime: 18000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      cache-null-values: true
